# Generated by Django 4.1 on 2022-09-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0008_remove_account_profile_profile_account'),
        ('Comic', '0033_alter_chapter_createat_alter_chapter_updateat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comic.chapter')),
                ('Comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comic.comic')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile')),
            ],
        ),
    ]
