# Generated by Django 4.1 on 2022-09-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0035_alter_chapter_createat_alter_chapter_updateat_and_more'),
        ('Viewed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vieweds', to='Comic.comic'),
        ),
    ]
