# Generated by Django 4.0.6 on 2022-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
