# Generated by Django 4.1 on 2022-09-04 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_phone_number_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
