# Generated by Django 4.1 on 2022-09-14 08:36

import Account.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('Gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl'), ('Other', 'Other')], default=('Boy', 'Boy'), max_length=20)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to=Account.models.Profile.update_filename)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='Avatar',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Phone',
        ),
        migrations.AddField(
            model_name='account',
            name='Profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.profile'),
        ),
    ]
