# Generated by Django 4.1 on 2022-09-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_profile_remove_account_avatar_remove_account_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='Account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Account.account'),
        ),
    ]
