# Generated by Django 4.1 on 2022-09-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_account_profile_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Account',
            field=models.OneToOneField(blank=True, default='img/profile/default.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Account.account'),
        ),
    ]
