# Generated by Django 4.1 on 2022-09-24 09:51

import Account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Account.account'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=Account.models.Profile.update_filename),
        ),
    ]
