# Generated by Django 4.1 on 2022-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
