# Generated by Django 4.1 on 2022-09-04 17:21

import Comic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0002_comic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='Banner',
            field=models.ImageField(blank=True, null=True, upload_to=Comic.models.Comic.update_filename),
        ),
    ]
