# Generated by Django 4.0.6 on 2022-09-05 10:30

import Comic.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0003_comic_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberChapter', models.FloatField(default=Comic.models.Chapter.getNumberChapter)),
                ('NameChapter', models.CharField(max_length=100)),
                ('CreateAt', models.DateField(default=datetime.datetime(2022, 9, 5, 17, 30, 40, 437656))),
                ('Views', models.BigIntegerField(default=0)),
                ('UpdateAt', models.DateField(default=datetime.datetime(2022, 9, 5, 17, 30, 40, 438592))),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 30, 40, 434663)),
        ),
        migrations.AddField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 30, 40, 434663)),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageNumber', models.IntegerField(default=0)),
                ('Page', models.ImageField(blank=True, null=True, upload_to=Comic.models.Page.update_filename)),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comic.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comic.comic'),
        ),
    ]
