# Generated by Django 4.0.6 on 2022-09-05 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0004_chapter_comic_createdat_comic_updateat_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 32, 13, 821324)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 32, 13, 821324)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 32, 13, 817704)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 5, 17, 32, 13, 817704)),
        ),
    ]
