# Generated by Django 4.1 on 2022-09-07 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0006_alter_chapter_createat_alter_chapter_numberchapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Comic.comic'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 19, 50, 49, 453019)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 19, 50, 49, 453019)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 19, 50, 49, 449736)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 7, 19, 50, 49, 449736)),
        ),
    ]
