# Generated by Django 4.1 on 2022-09-11 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0008_alter_chapter_createat_alter_chapter_updateat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='PreviousChapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Comic.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 53, 12, 357498)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 53, 12, 357498)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 53, 12, 353739)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 53, 12, 353739)),
        ),
    ]
