# Generated by Django 4.1 on 2022-09-13 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0014_alter_chapter_createat_alter_chapter_previouschapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic', to='Comic.comic'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 0, 36, 26, 387270)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='PreviousChapter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapterprevious', to='Comic.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 0, 36, 26, 387270)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 0, 36, 26, 383278)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 0, 36, 26, 383278)),
        ),
    ]
