# Generated by Django 4.1 on 2022-09-17 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_account_profile_profile_account'),
        ('Comic', '0020_alter_chapter_createat_alter_chapter_updateat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 12, 37, 826224))),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 12, 37, 825320)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 12, 37, 825320)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 12, 37, 821980)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 12, 37, 821980)),
        ),
        migrations.CreateModel(
            name='RepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comic.comment')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comic.chapter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Comic.comic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile'),
        ),
    ]
