# Generated by Django 4.1 on 2022-09-17 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0024_alter_chapter_createat_alter_chapter_updateat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 30, 58, 210390)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 30, 58, 210390)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 30, 58, 206341)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 30, 58, 206341)),
        ),
        migrations.AlterField(
            model_name='commentcomic',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 30, 58, 211327)),
        ),
    ]
