# Generated by Django 4.1 on 2022-09-17 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_account_profile_profile_account'),
        ('Comic', '0026_remove_repcomment_comment_remove_repcomment_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 37, 26, 223613))),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 37, 26, 223613)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 37, 26, 223613)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 37, 26, 218628)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 37, 26, 218628)),
        ),
        migrations.CreateModel(
            name='RepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comic.commentcomic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='commentcomic',
            name='Chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comic.chapter'),
        ),
        migrations.AddField(
            model_name='commentcomic',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Comic.comic'),
        ),
        migrations.AddField(
            model_name='commentcomic',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile'),
        ),
    ]
