# Generated by Django 4.1 on 2022-09-18 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_account_profile_profile_account'),
        ('Comic', '0029_commentcomic_reply_alter_chapter_comic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateAt', models.DateTimeField(default=datetime.datetime(2022, 9, 18, 21, 11, 51, 376777))),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 21, 11, 51, 375785)),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 21, 11, 51, 375785)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 21, 11, 51, 371803)),
        ),
        migrations.AlterField(
            model_name='comic',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 21, 11, 51, 371803)),
        ),
        migrations.DeleteModel(
            name='CommentComic',
        ),
        migrations.AddField(
            model_name='comiccomment',
            name='Chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comic.chapter'),
        ),
        migrations.AddField(
            model_name='comiccomment',
            name='Comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Comic.comic'),
        ),
        migrations.AddField(
            model_name='comiccomment',
            name='Reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Comic.comiccomment'),
        ),
        migrations.AddField(
            model_name='comiccomment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.profile'),
        ),
    ]
